name: 'Deploy Nikola to GitHub Pages'
description: 'Build the site using Nikola and deploy to GitHub Pages'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'zap'
  color: 'orange'
inputs:
  dry_run:
    description: 'Build without publishing code'
    default: false
    required: false
  apt_install:
    descrption: 'Extra APT packages to install from Ubuntu 20.04 repositories, space-separated'
    default: ''
    required: false
